style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/bojand/mdpage
options:
  commits:
    # filters:
    #   Type:
    #     - docs
    #     - enhance
    #     - feat
    #     - fix
    #     - build
    #     - ci
  commit_groups:
    title_maps:
      docs: Documentation
      doc: Documentation
      enhance: Enhancements
      feat: Features
      fix: Bug Fixes
      build: Build
      ci: Build
  header:
    pattern: "^(\\w*)?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE