full_page = false
title = "mdPage"
subtitle = "Simple documentation tool"
author = "Bojan D."
icon = "static/favicon.ico"
script = "(function () { hljs.initHighlightingOnLoad(); })()"

[[links]]
link_type = "script"
src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"
integrity = "sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0="
crossorigin = "anonymous"

[[links]]
link_type = "script"
src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/json.min.js"

[[links]]
link_type = "script"
src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/shell.min.js"

[[links]]
link_type = "style"
src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css"

[[contents]]
label = "Home"
file = "index.md"

[[contents]]
file = "install.md"

[[contents]]
file = "usage.md"

[[contents]]
file = "config.md"

[[contents]]
file = "examples.md"

[[contents]]
file = "todo.md"