name: build

on:
  push:
    branches:
    - master
    paths:
    - 'Cargo*'
    - 'src/**'
    - 'tests/**'
  pull_request:
    branches:
    - master
    paths:
    - 'Cargo*'
    - 'src/**'
    - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Install rustfm
      run: rustup component add rustfmt
    
    - name: Install clippy
      run: rustup component add clippy
    
    - name: Check format
      run: cargo fmt --all -- --check
    
    - name: Build
      run: cargo build
    
    - name: Test
      run: cargo test
    
    - name: Lint
      run: cargo clippy