name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rustfm
      run: rustup component add rustfmt
    - name: Install clippy
      run: rustup component add clippy
    - name: Check format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Lint
      run: cargo clippy