name: docs

on:
    push:
      branches:
      - master
      paths:
      - 'docs/*.sh'
      - 'docs/*.md'
      - 'docs/*/*.md'
      - 'docs/*/*/*.md'
      - 'docs/*/*/*/*.md'
      - 'docs/*/*/*/*/*.md'
    pull_request:
      branches:
      - master
      paths:
      - 'docs/*.sh'
      - 'docs/*.md'
      - 'docs/*/*.md'
      - 'docs/*/*/*.md'
      - 'docs/*/*/*/*.md'
      - 'docs/*/*/*/*/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Build mdpage CLI
      run: cargo build
    
    - name: Build
      run: |
        sh pwd
        sh ./docs/build.sh
    
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MSG: Update documentation
      run: |
        git config user.email "dbojan@gmail.com"
        git config user.name "Bojan"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        # git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)  