name: docs

on:
    push:
      branches:
      - master
      paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/docs.yml'
      - 'docs/*.sh'
      - 'docs/*.md'
      - 'docs/*/*.md'
      - 'docs/*/*/*.md'
      - 'docs/*/*/*/*.md'
      - 'docs/*/*/*/*/*.md'

jobs:
  build:
#     env:
#         RUST_LOG: info
        
    runs-on: ubuntu-latest

    steps:
    - name: Install mdpage
      run: cargo install mdpage
    
    - name: Build
      working-directory: .
      run: |
        pwd
        mdpage ${GITHUB_WORKSPACE}/docs/examples/basic
        mdpage ${GITHUB_WORKSPACE}/docs/examples/sections
        mdpage ${GITHUB_WORKSPACE}/docs/examples/full_page --full-page --title "Full Page" --subtitle "Full page example"
        mdpage ${GITHUB_WORKSPACE}/docs/examples/config
        mdpage ${GITHUB_WORKSPACE}/docs/examples/single_index --title "Single page" --subtitle "Single main page"
        mdpage ${GITHUB_WORKSPACE}/docs/examples/single_page --title "Single page" --subtitle "Single content page"
        mdpage ${GITHUB_WORKSPACE}/docs/examples/config_dir
        mdpage ${GITHUB_WORKSPACE}/docs
    
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_ACTION_TOKEN }}
        COMMIT_MSG: Update documentation
      run: |
        git config user.email "dbojan@gmail.com"
        git config user.name "Bojan"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)  
