name: docs

on:
    push:
      branches:
      - master
      paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/docs.yml'
      - 'docs/*.sh'
      - 'docs/*.md'
      - 'docs/*/*.md'
      - 'docs/*/*/*.md'
      - 'docs/*/*/*/*.md'
      - 'docs/*/*/*/*/*.md'

jobs:
  build:
        
    runs-on: ubuntu-latest

    steps:
    - name: Install mdpage
      run: |
        mkdir -p ~/bin
        curl -L -s https://github.com/bojand/mdpage/releases/latest/download/mdpage-x86_64-unknown-linux-gnu.tar.gz -o ~/bin/mdpage.tar.gz
        tar -xf ~/bin/mdpage.tar.gz

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: |
        ~/bin/mdpage ./docs/examples/basic
        ~/bin/mdpage ./docs/examples/sections
        ~/bin/mdpage ./docs/examples/full_page --full-page --title "Full Page" --subtitle "Full page example"
        ~/bin/mdpage ./docs/examples/config
        ~/bin/mdpage ./docs/examples/single_index --title "Single page" --subtitle "Single main page"
        ~/bin/mdpage ./docs/examples/single_page --title "Single page" --subtitle "Single content page"
        ~/bin/mdpage ./docs/examples/config_dir
        ~/bin/mdpage ./docs
    
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_ACTION_TOKEN }}
        COMMIT_MSG: Update documentation
      run: |
        git config user.email "dbojan@gmail.com"
        git config user.name "Bojan"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)  
