name: Release

on:
  push:
    tags:
      - v*

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
  release:
    needs: create
    name: Deploy Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - name: Install hub
      run: ci/install-hub.sh ${{ matrix.os }}
      shell: bash
    - name: Install Rustup
      run: ci/install-rustup.sh stable
      shell: bash
    - name: Install Rust
      run: ci/install-rust.sh stable
      shell: bash
    - name: Build and deploy artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ci/make-release.sh ${{ matrix.os }}
      shell: bash