name: Release

on:
  push:
    tags:
      - v*

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install hub
      run: |
        curl -LsSf https://github.com/github/hub/releases/download/v2.13.0/hub-linux-amd64-2.13.0.tgz -o hub.tgz
        mkdir hub
        tar -xzvf hub.tgz --strip=1 -C hub
        echo "##[add-path]$PWD/hub/bin"
      shell: bash
    - name: Create release
      run: hub release create ${GITHUB_REF}
      shell: bash
  release:
    needs: create
    name: Deploy Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - name: Install hub
      run: ci/install-hub.sh ${{ matrix.os }}
      shell: bash
    - name: Install Rustup
      run: ci/install-rustup.sh stable
      shell: bash
    - name: Install Rust
      run: ci/install-rust.sh stable
      shell: bash
    - name: Build and deploy artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ci/make-release.sh ${{ matrix.os }}
      shell: bash